setwd("~/GitHub/ExData_Plotting1")
HPC <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
HPC$Date <- as.Date(HPC$Date, "%d/%m/%Y")
HPC1 <- subset(HPC, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
HPC1$datetime <- strptime(paste(HPC1$Date, HPC1$Time), "%Y-%m-%d %H:%M:%S")
globalActivePower <- as.numeric(HPC1$Global_active_power)
subMetering1 <- as.numeric(HPC1$Sub_metering_1)
subMetering2 <- as.numeric(HPC1$Sub_metering_2)
subMetering3 <- as.numeric(HPC1$Sub_metering_3)
par(mfrow=c(1,1))
plot(HPC1$datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(HPC1$datetime, subMetering2, type="l", col="red")
lines(HPC1$datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.copy(png, file = "plot3.png", height = 480, width = 480)
dev.off()