setwd("~/GitHub/ExData_Plotting1")
HPC <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
HPC$Date <- as.Date(HPC$Date, "%d/%m/%Y")
HPC1 <- subset(HPC, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
HPC1$datetime <- strptime(paste(HPC1$Date, HPC1$Time), "%Y-%m-%d %H:%M:%S")
par(mfrow=c(1,1))
with(HPC1, plot(datetime, Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)"))
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()